sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: 1ALcWDy1QDjqSTOqOvwWA7Tk/0INxSiHFsyU8g8rmjP7E2iBDl5idGW2Rfnb+PcnH3I6TkrIia2awtMZn+GTmzYMHd0terKuk0udCcleNn9vW103PoNnhN5b08MCpuD+0qm7ahLmJorKGwLSeHIxZ+O0JxgE6Pm0UsqgP/YOa1obs8rDOn+gEZjNgncK8T3dYY2gYn0EL314MwSgsOCBHgCBYNfYxccw2KcnDtT8bCzCl/cpLycR/2Ql5bWFkiqFPlVEcNXz9DY5fYrMmhrzru484guwAgjmkGK1GsnmUO6guZ+F7humMPOIKQE6VfWXgemx8/iL2TaqTxu0asdCb3PQJLcamLC/QcEn/RMutpSzp+sj4BZTsya+8/LoQkXMe3aPPGSznG0woymfe44l/NMt10W82j/BiU9zJ/WszCV8viCeXiS2kWx/R3q3qjf1ZUEhz66GTAU2ZBQiBMkUhDMVSOMNrz6bJBTXR8HFs+mPZH9pOu2COj27A46CW5GQVo25kxRUFWI31knZqo+J6EQX39J/tnipNb8BRuoRIzQvLZtSkvRCDPAX+CkVAd5r7cVNEGdzG2TzdZFDthFvenCdlNRFAx+mH5Y1tiH86fR19qsvVemWrfg3exxdyoR8YKBt2bpkZI/vCEuqVkXvTjeOuUnDwOX+1vnTG842CTE=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/His-Last-Bow--An-Epilogue-of-Sherlock-Holmes_2350
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy